version: '3.8'

services:
  backend:
    build: .
    container_name: accessibility-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: accessibilitydb
      PORT: 3000
      OPENAI_API_KEY: your_openai_api_key_here
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: accessibility-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: accessibilitydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
